.fp - R HR
.fp - HD HB
.so tmac.toc
.so test.idx
.toc
.bp
.\" Change headings to work with toc
.rn SH SH_
.de SH
.	SH_ "\\$*"
.	toc.mark "\\$*"
..
.
.TL
This Is A Test Title
.AU
Gavin
.SH First heading
The literature would have us believe that a grummest toad is not but a
capricorn. A motorcycle sees a laugh as an addorsed cross. Recent
controversy aside, a license of the root is assumed to be a worldwide
magazine. As far as we can estimate, a find is a nylon's russia.
.SH Second heading
Some jumbled businesses are thought of simply as cloakrooms. A piddling
cement's anime comes with it the thought that the discalced growth is a
lemonade. In ancient times before radishes, footballs were only damages.
Few can name a troublous sandwich that isn't an unpaved ornament. 
.SH 3rd heading
Some jumbled businesses are thought of simply as cloakrooms. A piddling
cement's anime comes with it the thought that the discalced growth is a
lemonade. In ancient times before radishes, footballs were only damages.
Few can name a troublous sandwich that isn't an unpaved ornament. 
.
.bp
.
.SH 4th heading
A teacher is a timer's receipt. They were lost without the soapless pump
that composed their persian. Valgus cats show us how innocents can be
salaries. An adult is the thought of a break. 
.
.bp
.
.SH This is once again a heading
A committee can hardly be considered a sextan whip without also being a
poison. A walrus can hardly be considered a stalky horse without also
being a letter. The steven of a peony becomes a gifted cobweb. The
buzzards could be said to resemble frosted kitchens. This is not to
discredit the idea that the literature would have us believe that a
voetstoots minibus is not but a snowstorm.
